routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('404-tenant', 'errors.404-tenant')->name('404.tenant');

Auth::routes(['register' => true]);

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


Route::redirect('/', '/admin', 301);

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'lecom.auth']], function () {
    //Home/Requisiçoes
    Route::get('/', 'AdminController@index')->name('home');
    Route::get('requisicao/{codProcesso}', 'AdminController@showRequisicao')->name('requisicao.show');
    Route::post('requisicao/{acao}', 'AdminController@acaoRequisicao')->name('requisicao.acao');

    //Manutenção produtos
    Route::resource('produtos', 'ProdutoController')->except(['destroy', 'show']);

    //Manutenção tickets
    Route::resource('tickets', 'TicketController')->except(['destroy', 'show']);
    Route::get('tickets/import', 'TicketController@import')->name('tickets.import.index');
    Route::post('tickets/import', 'TicketController@importDo')->name('tickets.import.do');

    //Manutenção empresas
    Route::resource('empresas', 'EmpresaController')->except(['destroy']);
    //Manutenção empresa produtos
    Route::resource('empresa/{id}/produtos', 'EmpresaProdutoController', ['names' => 'empresa.produtos'])->except(['index', 'destroy']);

    //Manutenção pré-aprovados
    Route::get('pre-aprovados/{idEmpresa}/create', 'PreAprovadoController@create')->name('pre-aprovados.create');
    Route::post('pre-aprovado-redirect', 'PreAprovadoController@preAprovadoRedirect')->name('pre-aprovados.redirect');
    Route::post('pre-aprovado/destroy', 'PreAprovadoController@destroy')->name('pre-aprovados.destroy');
    Route::resource('pre-aprovados', 'PreAprovadoController')->except(['create', 'destroy', 'show']);

    Route::get('pre-aprovados/{idEmpresa}/import', 'PreAprovadoController@import')->name('pre-aprovados.import.index');
    Route::post('pre-aprovados/{idEmpresa}/import', 'PreAprovadoController@importDo')->name('pre-aprovados.import.do');


    //Tela erros de importação
    Route::get('import/{id}/failed', 'ImportController@failed')->name('import.failed');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group(['as' => 'cliente.', 'prefix' => '{cliente}', 'middleware' => ['lecom.auth']], function () {
    Route::get('/', 'ClienteController@index')->name('home');
    Route::post('/', 'ClienteController@verifyPreAprovado')->name('requisicao.verify');
    Route::get('/acompanhar-requisicao', 'ClienteController@acompanhaSolicitacao')->name('requisicao.acompanha');
    Route::post('/acompanhar-requisicao', 'ClienteController@acompanhaSolicitacaoDo')->name('requisicao.acompanha.do');
    Route::get('/{sku?}', 'ClienteController@PreAprovado')->name('requisicao.index');
    Route::post('/{sku?}', 'ClienteController@doPreAprovado')->name('requisicao.do');
});

app/Models/Produto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $connection = 'mysql';
    
    protected $fillable = [
                            "sku", 
                            "produto", 
                            "vid_conf", 
                            "biometria" //0 = Não | 1 = Sim | 2 = Ambos
                        ];

    public function empresas()
    {
        return $this->hasMany(EmpresaProduto::class);
        // return $this->belongsToMany(EmpresaProduto::class);
    }
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produto;
use Illuminate\Http\Request;

class ProdutoController extends Controller
{
    
    public function index()
    {
        $produtos = Produto::paginate(25);
        
         
        return view("produtos.index", compact("produtos"));
    }

    public function create()
    {
        return view("produtos.create-edit");
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'sku' => 'required|max:50|unique:produtos',
            'produto' => 'required|max:255',
        ]);

        Produto::create($request->all());
   
        return redirect()->route('admin.produtos.index')
                        ->with('success','Produto criado com sucesso.');
    }

    public function edit(Produto $produto)
    {
        //dd($produto);
        return view('produtos.create-edit', compact('produto'));
    }

    public function update(Request $request, Produto $produto)
    {
        $validatedData = $request->validate([
            'sku' => 'required|max:50|unique:produtos,sku,'.$produto->id,
            'produto' => 'required|max:255',
        ]);
        
        $dadosForm = $request->all();
        
        if (isset($dadosForm['vid_conf']))
            $dadosForm['vid_conf'] = 1;
        else
            $dadosForm['vid_conf'] = 0;
  
        $produto->update($dadosForm);
        
        return redirect()->route('admin.produtos.index')
                        ->with('success','Produto alterado com sucesso.');
    }

}

resources/views/produtos/create-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    
                    <h2 class="mb-4">{{(isset($produto)) ? "Editar" : "Adicionar"}} produto</h2>


                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    
                    <form method="POST" action="{{ (isset($produto)) ? route("admin.produtos.update", $produto->id)  :  route("admin.produtos.store")}}">
                        @csrf
                        @if(isset($produto))
                        @method('PUT')
                        @endif
                        <div class="form-row">

                            <div class="form-group col-md-3">
                                <label for="inputSKU">SKU</label>
                                <input type="text" name="sku" class="form-control" value="{{ (isset($produto)) ? $produto->sku : old('sku') }}">
                            </div>

                            <div class="form-group col-md-6">
                                <label for="inputProduto">Produto</label>
                                <input type="text" name="produto" class="form-control" value="{{ (isset($produto)) ? $produto->produto : old('produto') }}">
                            </div>

                            <div class="form-group col-md-1 text-center">
                                <label for="inputProduto">Vídeo Conf.</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="vid_conf" value="1" data-toggle="tooltip" title="Disponível videoconferência." {{ (isset($produto) ? ($produto->vid_conf ? 'checked' : '')  : (old('vid_conf') ? 'checked' : '') ) }}>
                                  </div>
                            </div>

                            <div class="form-group col-md-2 text-center">
                                <label for="inputProduto">Biometria</label>                                
                                <div>
                                    <label class="radio-inline" for="radioSim">
                                        <input type="radio" name="biometria" value="1" class="ml-1" {{ (isset($produto) ? ($produto->biometria == 1 ? 'checked' : '')  : (old('biometria') == 1 ? 'checked' : '') ) }}> Sim
                                    </label>
                                    
                                    <label class="radio-inline" for="radioNao">
                                        <input type="radio" name="biometria" value="0" class="ml-1" {{ (isset($produto) ? ($produto->biometria == 0 ? 'checked' : '')  : 'checked'  ) }}> Não
                                    </label>
                                    
                                    <label class="radio-inline" for="radioTalvez">
                                        <input type="radio" name="biometria" value="2" class="ml-1" {{ (isset($produto) ? ($produto->biometria == 2 ? 'checked' : '')  : (old('biometria') == 3 ? 'checked' : '') ) }}> Ambos
                                    </label>
                                </div>
                                

                            </div>
                            
                        </div>

                        <button type="submit" class="btn btn-primary">{{(isset($produto)) ? 'Alterar' : 'Cadastrar'}}</button>

                        <a href="{{route('admin.produtos.index')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts-footer')
<script type="text/javascript">
    $(document).ready(function($){
        $('.form-check-input').tooltip();
    })
</script>
@endpush

resources/views/produtos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Produtos</h3>
                </div>

                <div class="card-body">
                    
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif

                    <h6>
                        <a href="{{route('admin.produtos.create')}}" class="btn btn-success">
                            Adicionar
                        </a>
                        
                        <a href="{{route('admin.home')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </h6>
                    <div class="table-responsive">
                        <table class="table table-hover text-center">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">SKU</th>
                                    <th scope="col">Produto</th>
                                    <th scope="col" data-toggle="tooltip" title="Disponível videoconferência.">Videoconf.</th>
                                    <th scope="col" data-toggle="tooltip" title="Obrigatório biometria cadastrada.">Biometria</th>
                                </tr>
                            </thead>
                            <tbody> 
                                @forelse ($produtos as $produto)
                                <tr data-link="{{route('admin.produtos.edit', $produto->id)}}">
                                    <th scope="row">{{$produto->id}}</th>
                                    <td>{{$produto->sku}}</td>
                                    <td>{{$produto->produto}}</td>
                                    <td>{{($produto->vid_conf) ? 'Sim' : 'Não'}}</td>
                                    <td>
                                        @switch($produto->biometria)
                                            @case(1)
                                                Sim
                                                @break
                                            @case(2)
                                                Ambos
                                                @break
                                            @default
                                                Não
                                        @endswitch
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="5">Nenhum produto cadastrado!</td>
                                </tr>
                                @endforelse
                                
                            </tbody>
                        </table>
                    </div>
                    {{ $produtos->onEachSide(0)->links() }}

                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts-footer')
    @component('components.table-click')  
    @endcomponent

    <script type="text/javascript">
        $(document).ready(function($){
            $('table thead tr th').tooltip();
        })
    </script>
@endpush