routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('404-tenant', 'errors.404-tenant')->name('404.tenant');

Auth::routes(['register' => true]);

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


Route::redirect('/', '/admin', 301);

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'lecom.auth']], function () {
    //Home/Requisiçoes
    Route::get('/', 'AdminController@index')->name('home');
    Route::get('requisicao/{codProcesso}', 'AdminController@showRequisicao')->name('requisicao.show');
    Route::post('requisicao/{acao}', 'AdminController@acaoRequisicao')->name('requisicao.acao');

    //Manutenção produtos
    Route::resource('produtos', 'ProdutoController')->except(['destroy', 'show']);

    //Manutenção tickets
    Route::resource('tickets', 'TicketController')->except(['destroy', 'show']);
    Route::get('tickets/import', 'TicketController@import')->name('tickets.import.index');
    Route::post('tickets/import', 'TicketController@importDo')->name('tickets.import.do');

    //Manutenção empresas
    Route::resource('empresas', 'EmpresaController')->except(['destroy']);
    //Manutenção empresa produtos
    Route::resource('empresa/{id}/produtos', 'EmpresaProdutoController', ['names' => 'empresa.produtos'])->except(['index', 'destroy']);

    //Manutenção pré-aprovados
    Route::get('pre-aprovados/{idEmpresa}/create', 'PreAprovadoController@create')->name('pre-aprovados.create');
    Route::post('pre-aprovado-redirect', 'PreAprovadoController@preAprovadoRedirect')->name('pre-aprovados.redirect');
    Route::post('pre-aprovado/destroy', 'PreAprovadoController@destroy')->name('pre-aprovados.destroy');
    Route::resource('pre-aprovados', 'PreAprovadoController')->except(['create', 'destroy', 'show']);

    Route::get('pre-aprovados/{idEmpresa}/import', 'PreAprovadoController@import')->name('pre-aprovados.import.index');
    Route::post('pre-aprovados/{idEmpresa}/import', 'PreAprovadoController@importDo')->name('pre-aprovados.import.do');


    //Tela erros de importação
    Route::get('import/{id}/failed', 'ImportController@failed')->name('import.failed');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group(['as' => 'cliente.', 'prefix' => '{cliente}', 'middleware' => ['lecom.auth']], function () {
    Route::get('/', 'ClienteController@index')->name('home');
    Route::post('/', 'ClienteController@verifyPreAprovado')->name('requisicao.verify');
    Route::get('/acompanhar-requisicao', 'ClienteController@acompanhaSolicitacao')->name('requisicao.acompanha');
    Route::post('/acompanhar-requisicao', 'ClienteController@acompanhaSolicitacaoDo')->name('requisicao.acompanha.do');
    Route::get('/{sku?}', 'ClienteController@PreAprovado')->name('requisicao.index');
    Route::post('/{sku?}', 'ClienteController@doPreAprovado')->name('requisicao.do');
});

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $connection = 'mysql';
    
    protected $fillable = ["produto_id", "ticket", "utilizado", "origem"];

    public function produto()
    {
        return $this->hasOne(Produto::class, 'id', 'produto_id');
    }

}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Imports\TicketsImport;
use App\Models\Import;
use App\Models\Produto;
use App\Models\Ticket;
use Illuminate\Http\Request;

class TicketController extends Controller
{
    
    public function index()
    {
        $tickets = Ticket::with('produto')->paginate(25);

        return view("tickets.index", compact("tickets"));
    }

    public function create()
    {
        $produtos = Produto::all(["id", "sku", "produto"]);
        
        return view("tickets.create-edit", compact("produtos"));
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'ticket' => 'required|max:50|unique:tickets',
            'produto_id' => 'required'
        ]);

        Ticket::create($request->all());
   
        return redirect()->route('admin.tickets.index')
                        ->with('success','ticket criado com sucesso.');
    }

    public function edit(ticket $ticket)
    {
        $produtos = Produto::all(["id", "sku", "produto"]);

        return view('tickets.create-edit', compact('ticket', 'produtos'));
    }

    public function update(Request $request, ticket $ticket)
    {
        $validatedData = $request->validate([
            'ticket' => 'required|max:50|unique:tickets,ticket,'.$ticket->id,
            'produto_id' => 'required',
        ]);
  
        $dadosForm = $request->all();

        if (isset($dadosForm['utilizado']))
            $dadosForm['utilizado'] = 1;
        else
            $dadosForm['utilizado'] = 0;

        $ticket->update($dadosForm);
  
        return redirect()->route('admin.tickets.index')
                        ->with('success','Ticket alterado com sucesso.');
    }

    public function import()
    {
        $imports = Import::where('tabela', 'tickets')->paginate(25);

        return view('tickets.import', compact('imports'));
    }

    public function importDo(Request $request)
    {

        $validatedData = $request->validate([
            'arquivo' => 'required|max:2000|mimes:xlsx,xls,csv'
        ]);
        
        $import = new TicketsImport();
        $import->import(request()->file('arquivo'));
        
        $tableImport = Import::create([
            'tabela'    => 'tickets',
            'arquivo'   => request()->file('arquivo')->getClientOriginalName(),
            'total'     => $import->totalCount,
            'sucesso'   => $import->successCount,
        ]);
        
        foreach ($import->failures() as $failure) {
            $tableImport->faileds()->create([
                'linha'     => $failure->row(),
                'atributo'  => $failure->attribute(),
                'erros'     => $failure->errors(),
                'valores'   => $failure->values()
            ]);
        }

        return redirect()->route('admin.tickets.import.index')
                        ->with('success', 'Importação concluida!');
                        
    }

}

resources/views/tickets/create-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    
                    <h2 class="mb-4">{{(isset($ticket)) ? "Editar" : "Adicionar"}} ticket</h2>


                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    
                    <form method="POST" action="{{ (isset($ticket)) ? route("admin.tickets.update", $ticket->id)  :  route("admin.tickets.store")}}">
                        @csrf
                        @if(isset($ticket))
                        @method('PUT')
                        @endif
                        <div class="form-row">
                            
                            <div class="form-group col-md-3">
                                <label for="inputTicket">Ticket</label>
                                <input type="text" name="ticket" class="form-control" value="{{ (isset($ticket)) ? $ticket->ticket : old('ticket') }}">
                            </div>

                            <div class="form-group col-md-8">
                                <label for="inputSKU">Produto</label>
                                <select class="form-control" name="produto_id">
                                    <option value>Selecione uma opção</option>
                                    @forelse ($produtos as $produto)
                                    <option value="{{$produto->id}}" {{ (isset($ticket) ? ($ticket->produto_id == $produto->id ? 'selected' : '') : (old('produto_id') == $produto->id) ? 'selected' : '')  }}>{{ $produto->sku }} - {{ $produto->produto }}</option>
                                    @empty
                                        <option value>Não existem produtos cadastrado</option>
                                    @endforelse
                                </select>
                            </div>

                            <div class="form-group col-md-1">
                                <label for="inputProduto"></label>
                                <div class="form-check mt-2">
                                    <input class="form-check-input" type="checkbox" name="utilizado" {{ (isset($ticket) ? ($ticket->utilizado ? 'checked' : '')  : (old('utilizado') ? 'checked' : '') ) }} {{(isset($ticket)) ? '' : 'disabled' }}>
                                    <label class="form-check-label" for="inputProduto">
                                        Utilizado
                                    </label>
                                </div>
                            </div>

                        </div>

                        <button type="submit" class="btn btn-primary">{{(isset($ticket)) ? 'Alterar' : 'Cadastrar'}}</button>

                        <a href="{{route('admin.tickets.index')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tickets/import.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    
                    <h2 class="mb-4">Importar tickets</h2>

                    @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ $message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    
                    <form action="{{ route('admin.tickets.import.do') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <input type="file" name="arquivo" class="form-control" accept=".xls,.xlsx,.csv">
                          
                        <br><br>
                        
                        <button class="btn btn-success">Importar</button>

                        <a href="{{route('admin.tickets.index')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </form>

                    <div class="mt-5">
                        <div class="table-responsive">
                            <table class="table table-hover text-center">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Arquivo</th>
                                        <th scope="col">Total</th>
                                        <th scope="col">Sucesso</th>
                                        <th scope="col">Falha</th>
                                        <th scope="col">Data</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    @forelse ($imports as $import)
                                    <tr data-link="{{route('admin.import.failed', $import->id)}}">
                                        <th scope="row">{{$import->id}}</th>
                                        <td>{{$import->arquivo}}</td>
                                        <td>{{$import->total}}</td>
                                        <td>{{$import->sucesso}}</td>
                                        <td>{{ $import->total - $import->sucesso }}</td>
                                        <td>{{ \Carbon\Carbon::parse($import->created_at)->format('d/m/Y H:i:s') }}</td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="7">Nenhuma importação efetuada!</td>
                                    </tr>
                                    @endforelse
                                    
                                </tbody>
                            </table>
                        </div>
    
                        {{ $imports->onEachSide(0)->links() }}
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts-footer')
    @component('components.table-click')  
    @endcomponent
@endpush

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Tickets</h3>
                </div>

                <div class="card-body">
                    
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif

                    <h6>
                        <a href="{{route('admin.tickets.create')}}" class="btn btn-success">
                            Adicionar
                        </a>

                        <a href="{{route('admin.tickets.import.index')}}" class="btn btn-primary">
                            Importar
                        </a>
                        
                        <a href="{{route('admin.home')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </h6>
                    <div class="table-responsive">
                        <table class="table table-hover text-center">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Ticket</th>
                                    <th scope="col">SKU</th>
                                    <th scope="col">Produto</th>
                                    <th scope="col">Utilizado</th>
                                    <th scope="col">Origem</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                @forelse ($tickets as $ticket)
                                <tr data-link="{{route('admin.tickets.edit', $ticket->id)}}">
                                    <th scope="row">{{$ticket->id}}</th>
                                    <td>{{$ticket->ticket}}</td>
                                    <td>{{$ticket->produto->sku}}</td>
                                    <td>{{$ticket->produto->produto}}</td>
                                    <td>{{($ticket->utilizado) ? 'Sim' : 'Não'}}</td>
                                    <td>{{($ticket->origem) ? 'Import.' : 'Manual'}}</td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="7">Nenhum ticket cadastrado!</td>
                                </tr>
                                @endforelse
                                
                            </tbody>
                        </table>
                    </div>

                    {{ $tickets->onEachSide(0)->links() }}

                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts-footer')
    @component('components.table-click')  
    @endcomponent
@endpush