routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('404-tenant', 'errors.404-tenant')->name('404.tenant');

Auth::routes(['register' => true]);

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


Route::redirect('/', '/admin', 301);

Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'lecom.auth']], function () {
    //Home/Requisiçoes
    Route::get('/', 'AdminController@index')->name('home');
    Route::get('requisicao/{codProcesso}', 'AdminController@showRequisicao')->name('requisicao.show');
    Route::post('requisicao/{acao}', 'AdminController@acaoRequisicao')->name('requisicao.acao');

    //Manutenção produtos
    Route::resource('produtos', 'ProdutoController')->except(['destroy', 'show']);

    //Manutenção tickets
    Route::resource('tickets', 'TicketController')->except(['destroy', 'show']);
    Route::get('tickets/import', 'TicketController@import')->name('tickets.import.index');
    Route::post('tickets/import', 'TicketController@importDo')->name('tickets.import.do');

    //Manutenção empresas
    Route::resource('empresas', 'EmpresaController')->except(['destroy']);
    //Manutenção empresa produtos
    Route::resource('empresa/{id}/produtos', 'EmpresaProdutoController', ['names' => 'empresa.produtos'])->except(['index', 'destroy']);

    //Manutenção pré-aprovados
    Route::get('pre-aprovados/{idEmpresa}/create', 'PreAprovadoController@create')->name('pre-aprovados.create');
    Route::post('pre-aprovado-redirect', 'PreAprovadoController@preAprovadoRedirect')->name('pre-aprovados.redirect');
    Route::post('pre-aprovado/destroy', 'PreAprovadoController@destroy')->name('pre-aprovados.destroy');
    Route::resource('pre-aprovados', 'PreAprovadoController')->except(['create', 'destroy', 'show']);

    Route::get('pre-aprovados/{idEmpresa}/import', 'PreAprovadoController@import')->name('pre-aprovados.import.index');
    Route::post('pre-aprovados/{idEmpresa}/import', 'PreAprovadoController@importDo')->name('pre-aprovados.import.do');


    //Tela erros de importação
    Route::get('import/{id}/failed', 'ImportController@failed')->name('import.failed');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group(['as' => 'cliente.', 'prefix' => '{cliente}', 'middleware' => ['lecom.auth']], function () {
    Route::get('/', 'ClienteController@index')->name('home');
    Route::post('/', 'ClienteController@verifyPreAprovado')->name('requisicao.verify');
    Route::get('/acompanhar-requisicao', 'ClienteController@acompanhaSolicitacao')->name('requisicao.acompanha');
    Route::post('/acompanhar-requisicao', 'ClienteController@acompanhaSolicitacaoDo')->name('requisicao.acompanha.do');
    Route::get('/{sku?}', 'ClienteController@PreAprovado')->name('requisicao.index');
    Route::post('/{sku?}', 'ClienteController@doPreAprovado')->name('requisicao.do');
});

app/Models/PreAprovado.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PreAprovado extends Model
{
    protected $connection = 'mysql';
    
    protected $fillable = [
        'empresa_id',
        'produto_id',
        'cpf',
        'nome',
        'email',
        'celular',
        'telefone',
        'personalizado1',
        'personalizado2',
        'personalizado3',
        'utilizado',
        'origem'
    ];

    public function empresa()
    {
        return $this->hasOne(Empresa::class, 'id', 'empresa_id');
    }

}

app/Http/Controllers/PreAprovadoController.php
<?php

namespace App\Http\Controllers;

use App\Imports\PreAprovadosImport;
use App\Models\Import;
use App\Models\Empresa;
use App\Models\PreAprovado;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\SoftDeletes;

class PreAprovadoController extends Controller
{
    use SoftDeletes;
    
    public function index(Request $request)
    {
        $filtrarPor = $request->get("filtrarPor");
        $operadorFiltro = $request->get("operadorFiltro");
        $valorFiltro = $request->get("valorFiltro");
        $empresa_id = $request->get("empresa");

        $filtro = ["filtrarPor" => $filtrarPor, "operadorFiltro" => $operadorFiltro, "valorFiltro" => $valorFiltro, "empresa" => $empresa_id];

        $empresas = Empresa::all(["id", "nome"]);

        $preAprovados = PreAprovado::query()
                                ->with('empresa');

        if ($filtrarPor) {
            if ($filtrarPor == "utilizado") 
                $valorFiltro = ( \Str::upper($valorFiltro) === "SIM" ? 1 : 0 );
            if ($filtrarPor == "origem" ) 
                $valorFiltro = ( \Str::upper($valorFiltro) === "MANUAL" ? 0 : 1 );

            $preAprovados = aplicaFiltroModel($preAprovados, $filtrarPor, $operadorFiltro, $valorFiltro);
        }

        if ($empresa_id)
            $preAprovados->where('empresa_id', $empresa_id);
        
        $preAprovados =   $preAprovados->paginate(25);

        return view("pre-aprovados.index", compact("preAprovados", "empresas", "filtro"));
    }

    public function preAprovadoRedirect(Request $request)
    {
        $validatedData = $request->validate([
            'empresa_id' => 'required|exists:mysql.empresas,id',
            'action' => 'required|in:create,import'
        ], [],
        [
            "empresa_id" => "empresa",
            "action" => "ação",
        ]);


        if ($request->get("action") == "create")
            return redirect()->route("admin.pre-aprovados.create", $request->get("empresa_id"));
        else
            return redirect()->route("admin.pre-aprovados.import.index", $request->get("empresa_id"));
    }

    public function create($idEmpresa)
    {
        $empresa = Empresa::with('produtos')->find($idEmpresa);

        return view("pre-aprovados.create-edit", compact("empresa"));
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate(['empresa_id' => 'required|exists:mysql.empresas,id']);

        $empresa = Empresa::find($request->get("empresa_id"));
/*
$request->validate([
    'cpf'               => 'max:14|unique:pre_aprovados,cpf,NULL,id,empresa_id,'.$request->get('empresa_id').($empresa->consiste_cpf ? '|required' : ''),
            'nome'              => 'required|max:50',
            'email'             => 'sometimes|nullable|email',
            'celular'           => 'max:15',
            'telefone'          => 'max:15',
            'personalizado1'    => 'max:30'.($empresa->valida_personalizado1 ? '|required' : '').($empresa->valida_personalizado1 ? '|unique:pre_aprovados,personalizado1,NULL,id,empresa_id,'.$request->get('empresa_id') : ''),
            'personalizado2'    => 'max:30'.($empresa->valida_personalizado2 ? '|required' : '').($empresa->valida_personalizado2 ? '|unique:pre_aprovados,personalizado2,NULL,id,empresa_id,'.$request->get('empresa_id') : ''),
            'personalizado3'    => 'max:30'.($empresa->valida_personalizado3 ? '|required' : '').($empresa->valida_personalizado3 ? '|unique:pre_aprovados,personalizado3,NULL,id,empresa_id,'.$request->get('empresa_id') : ''),
]);
*/
        $validatedData = $request->validate([
            'cpf'               => 'max:14'.($empresa->consiste_cpf ? '|required' : ''),
            'nome'              => 'max:50',
            'email'             => 'sometimes|nullable|email',
            'celular'           => 'max:15',
            'telefone'          => 'max:15',
            'personalizado1'    => 'max:30'.($empresa->valida_personalizado1 ? '|required' : ''),
            'personalizado2'    => 'max:30'.($empresa->valida_personalizado2 ? '|required' : ''),
            'personalizado3'    => 'max:30'.($empresa->valida_personalizado3 ? '|required' : ''),
        ], [],
        [
            "personalizado1" => str_replace('_', ' ',$empresa->personalizado1),
            "personalizado2" => str_replace('_', ' ',$empresa->personalizado2),
            "personalizado3" => str_replace('_', ' ',$empresa->personalizado3),
        ]);
        
        PreAprovado::create($request->all());
        
        return redirect()->route('admin.pre-aprovados.index')
                        ->with('success','Pré-aprovado criado com sucesso.');
    }

    public function edit(PreAprovado $preAprovado)
    {
        $empresa = Empresa::with('produtos')->find($preAprovado->empresa_id);
        
        return view('pre-aprovados.create-edit', compact('preAprovado', 'empresa'));
    }
    
    public function destroy(Request $request)
    {

        $validatedData = $request->validate([
            'id'   => 'required|array|max:30',
        ], [
            'required'      => 'Selecione pelo menos uma opção.',
            'max'           => 'São permitidos no máximo 30 processos por operação.'
        ]);

        $errors = "";
        foreach ($request->id as $id) {
            $preAprovado = PreAprovado::find($id);
            if ($preAprovado) {
                $delete = $preAprovado->delete();
                if (!$delete)
                    $errors .= $id . ", ";    
            } else
                $errors .= $id . ", ";
        }

        if ($errors != "")
            return redirect()->back()->withErrors("Não foi possível EXCLUIR o(s) id(s) : " . \Str::beforeLast($errors, ',') .".");
        else
            return redirect()->back()->with('success', "Operação efetuada com sucesso!");
    }

    public function update(Request $request, PreAprovado $preAprovado)
    {
        $validatedData = $request->validate(['empresa_id' => 'required|exists:mysql.empresas,id']);

        $empresa = Empresa::find($request->get("empresa_id"));

        $validatedData = $request->validate([
            'cpf'               => 'max:14'.($empresa->consiste_cpf ? '|required' : ''),
            'nome'              => 'max:50',
            'email'             => 'sometimes|nullable|email',
            'celular'           => 'max:15',
            'telefone'          => 'max:15',
            'personalizado1'    => 'max:30'.($empresa->valida_personalizado1 ? '|required' : ''),
            'personalizado2'    => 'max:30'.($empresa->valida_personalizado2 ? '|required' : ''),
            'personalizado3'    => 'max:30'.($empresa->valida_personalizado3 ? '|required' : ''),
        ], [],
        [
            "personalizado1" => str_replace('_', ' ',$empresa->personalizado1),
            "personalizado2" => str_replace('_', ' ',$empresa->personalizado2),
            "personalizado3" => str_replace('_', ' ',$empresa->personalizado3),
        ]);

        $dadosForm = $request->all();

        if (isset($dadosForm['utilizado']))
            $dadosForm['utilizado'] = 1;
        else
            $dadosForm['utilizado'] = 0;
        
        $preAprovado->update($dadosForm);
  
        return redirect()->route('admin.pre-aprovados.index')
                        ->with('success','Pré-aprovado alterado com sucesso.');
    }

    public function import($idEmpresa)
    {
        $imports = Import::where('tabela', 'Pré-aprovados')
                        ->where('external_id', $idEmpresa)
                        ->paginate(25);

        return view('pre-aprovados.import', compact('idEmpresa','imports'));
    }

    public function importDo($idEmpresa, Request $request)
    {
        $request['empresa_id'] = $idEmpresa;
        $validatedData = $request->validate([
            'arquivo' => 'required|max:2000|mimes:xlsx,xls,csv',
            'empresa_id' => 'required|exists:mysql.empresas,id'
        ]);

        $empresa = Empresa::with('produtos')->find($request->get("empresa_id"));

        //dd($empresa->produtos->contains('id', '1'));
        
        $import = new PreAprovadosImport();
        $import->setEmpresa($empresa);
        $import->import(request()->file('arquivo'), "LayoutUsers");
        
        $tableImport = Import::create([
            'external_id'   => $idEmpresa,
            'tabela'        => 'Pré-aprovados',
            'arquivo'       => request()->file('arquivo')->getClientOriginalName(),
            'total'         => $import->totalCount,
            'sucesso'       => $import->successCount,
        ]);
        
        foreach ($import->failures() as $failure) {
            $tableImport->faileds()->create([
                'linha'     => $failure->row(),
                'atributo'  => $failure->attribute(),
                'erros'     => $failure->errors(),
                'valores'   => $failure->values()
            ]);
        }

        return redirect()->route('admin.pre-aprovados.import.index', $empresa->id)
                        ->with('success', 'Importação concluida!');
                        
    }

}

resources/views/pre-aprovados/create-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    
                    <h2 class="mb-4">{{(isset($preAprovado)) ? "Editar" : "Adicionar"}} Pré-aprovado</h2>

                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    
                    <form method="POST" action="{{ (isset($preAprovado)) ? route("admin.pre-aprovados.update", $preAprovado->id)  :  route("admin.pre-aprovados.store")}}">
                        @csrf
                        @if(isset($preAprovado))
                        @method('PUT')
                        @endif
                        <input type="hidden" name="empresa_id" value="{{$empresa->id}}">
                        <div class="form-row">
                            
                            <div class="form-group col-md-2">
                                <label for="inputCpf" class="{{($empresa->consiste_cpf ? 'required' : '')}}">Cpf</label>
                                <input type="text" name="cpf" class="form-control cpf" value="{{ (isset($preAprovado)) ? $preAprovado->cpf : old('cpf') }}" data-mask="000.000.000-00" data-mask-reverse="true">
                            </div>

                            <div class="form-group col-md-6">
                                <label for="inputNome">Nome</label>
                                <input type="text" name="nome" class="form-control" value="{{ (isset($preAprovado)) ? $preAprovado->nome : old('nome') }}">
                            </div>

                            <div class="form-group col-md-2">
                                <label for="inputCelular">Celular</label>
                                <input type="text" name="celular" class="form-control" value="{{ (isset($preAprovado)) ? $preAprovado->celular : old('celular') }}" data-mask="(00) 00000-0000">
                            </div>

                            
                            <div class="form-group col-md-2">
                                <label for="inputTelefone">Telefone</label>
                                <input type="text" name="telefone" class="form-control" value="{{ (isset($preAprovado)) ? $preAprovado->telefone : old('telefone') }}" data-mask="(00) 0000-0000">
                            </div>

                        </div>
                        
                        <div class="form-row">

                            <div class="form-group col-md-6">
                                <label for="inputEmail">Email</label>
                                <input type="" name="email" class="form-control" value="{{ (isset($preAprovado)) ? $preAprovado->email : old('email') }}">
                            </div>
                            
                            <div class="form-group col-md-5">
                                <label for="inputSKU">Produto</label>
                                <select class="form-control" name="produto_id">
                                    <option value>Selecione uma opção</option>
                                    @forelse ($empresa->produtos as $produto)
                                    <option value="{{$produto->id}}" {{ (isset($preAprovado) ? ($preAprovado->produto_id == $produto->id ? 'selected' : '') : (old('produto_id') == $produto->id) ? 'selected' : '')  }}>{{ $produto->sku }} - {{ $produto->produto }}</option>
                                    @empty
                                        <option value>Não existem produtos cadastrado</option>
                                    @endforelse
                                </select>
                            </div>
                            
                            <div class="form-group col-md-1">
                                <label for="inputProduto"></label>
                                <div class="form-check mt-2">
                                    <input class="form-check-input" type="checkbox" name="utilizado" {{ (isset($preAprovado) ? ($preAprovado->utilizado ? 'checked' : '')  : (old('utilizado') ? 'checked' : '') ) }} {{(isset($preAprovado)) ? '' : 'disabled' }}>
                                    <label class="form-check-label" for="inputProduto">
                                        Utilizado
                                    </label>
                                </div>
                            </div>

                        </div>

                        <div class="form-row">
                            @for ($i = 1; $i <= 3; $i++)
                                @if ($empresa->{"personalizado".$i})
                            <div class="form-group col-md-4">
                                <label for="inputPersonalizado{{$i}}" class="{{($empresa->{"valida_personalizado".$i} ? 'required' : '')}}">{{ ucwords(str_replace('_', ' ', $empresa->{"personalizado".$i})) }}</label>
                                <input type="text" name="personalizado{{$i}}" class="form-control" value="{{ (isset($preAprovado)) ? $preAprovado->{"personalizado".$i} : old( "personalizado".$i ) }}">
                            </div>
                                
                                @endif
                            @endfor 
                        </div>

                        <button type="submit" class="btn btn-primary">{{(isset($preAprovado)) ? 'Alterar' : 'Cadastrar'}}</button>

                        <a href="{{route('admin.pre-aprovados.index')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<!--JQuery-->
<script src="{{url('/assets/js/jquery.min.js')}}"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
@endpush

@push('scripts-footer')
<!--JQuery Mask-->
<script src="{{url('/assets/js/jquery.mask.min.js')}}"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<script type="text/javascript">
    $.jMaskGlobals.watchDataMask= true;
    $(document).ready(function($){
        $('input:checkbox').tooltip();
    })
</script>
@endpush

resources/views/pre-aprovados/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Pré-aprovados</h3>
                </div>

                <div class="card-body">
                    
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    @if ($errors->any())
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                    <form id="form" method="POST" action="{{route('admin.pre-aprovados.redirect')}}">
                    @csrf
                    <h6>
                        <div class="form-group">
                            <label for="inputSKU">Empresa</label>
                            <select class="form-control" name="empresa_id">
                                <option value>Selecione uma opção</option>
                                @forelse ($empresas as $empresa)
                                <option value="{{$empresa->id}}" {{(isset($filtro["empresa"]) && $filtro["empresa"] == $empresa->id ? 'selected' : '')}} {{ (isset($empresa) ? ($empresa->empresa_id == $empresa->id ? 'selected' : '') : (old('empresa_id') == $empresa->id) ? 'selected' : '')  }}>{{ $empresa->nome }}</option>
                                @empty
                                    <option value>Não existem empresas cadastrada</option>
                                @endforelse
                            </select>
                        </div>
                        
                        <button type="" class="btn btn-success" name="action" value="create">
                            Adicionar
                        </button>

                        <button type="" class="btn btn-primary" name="action" value="import">
                            Importar
                        </button>
                        
                        <a href="{{route('admin.home')}}" class="btn btn-secondary">
                            Voltar
                        </a>
                    </h6>
                    </form>

                    <div class="d-flex flex-wrap bd-highlight mb-3">
                        <div class="p-2 bd-highlight">
                            <a href="" class="btn btn-danger btn-sm mb-1" data-toggle="modal" data-target="#modalConfirm" data-acao="EXCLUIR" data-url="">
                                Excluir
                            </a>
                        </div>
                    </div>

                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Filtro</h5>
                            <form id="formFiltro" class="form">
                                @if (Request::has('empresa'))
                                <input type="hidden" name="empresa" value="{{ Request::get('empresa')}}">    
                                @endif
                                
                                <div class="d-flex flex-wrap justify-content-center bd-highlight mb-3">

                                    <div class="col-md-2">
                                        <select class="form-control" name="filtrarPor">
                                            <option value>Selecione uma opção</option>
                                            <option value='id' {{($filtro["filtrarPor"] == "id") ? "selected" : "" }}>Código</option>
                                            <option value='nome' {{($filtro["filtrarPor"] == "nome") ? "selected" : "" }}>Nome</option>
                                            <option value='utilizado' {{($filtro["filtrarPor"] == "utilizado") ? "selected" : "" }}>Utilizado</option>
                                            <option value='origem' {{($filtro["filtrarPor"] == "origem") ? "selected" : "" }}>Origem</option>
                                        </select>
                                    </div>

                                    <div class="col-md-2">
                                        <select class="form-control" name="operadorFiltro">
                                            <option value='=' {{($filtro["operadorFiltro"] == "=") ? "selected" : "" }}>É igual a...</option>
                                            <option value='!=' {{($filtro["operadorFiltro"] == "!=") ? "selected" : "" }}>É diferente de...</option>
                                            <option value='0' {{($filtro["operadorFiltro"] == "0") ? "selected" : "" }}>Começa com...</option>
                                            <option value='1' {{($filtro["operadorFiltro"] == "1") ? "selected" : "" }}>Termina com...</option>
                                            <option value='2' {{($filtro["operadorFiltro"] == "2") ? "selected" : "" }}>Contém...</option>
                                            <option value='3' {{($filtro["operadorFiltro"] == "3") ? "selected" : "" }}>Não contém...</option>
                                        </select>
                                    </div>

                                    <div class="col-md-7">
                                        <input type="text" name="valorFiltro" class="form-control" value="{{ $filtro["valorFiltro"] }}">
                                    </div>

                                    <div class="col-md-1">
                                        <button type="submit" class="btn btn-dark">Filtrar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div class="table-responsive">
                            <form id="table" action="{{route('admin.pre-aprovados.destroy')}}" method="POST">
                            @csrf
                            <table class="table table-hover text-center">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th>&nbsp<input class="form-check-input" type="checkbox" id="selectAll"></th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Empresa</th>
                                        <th scope="col">Utilizado</th>
                                        <th scope="col">Origem</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    @forelse ($preAprovados as $preAprovado)
                                    <tr data-link="{{route('admin.pre-aprovados.edit', $preAprovado->id)}}">
                                        <th scope="row">{{$preAprovado->id}}</th>
                                        <td>
                                            @if (!$preAprovado->utilizado)
                                            &nbsp<input name="id[]" class="form-check-input" type="checkbox" value="{{$preAprovado->id}}">
                                            @endif
                                        </td>
                                        <td>{{$preAprovado->nome}}</td>
                                        <td>{{$preAprovado->empresa->nome}}</td>
                                        <td>{{($preAprovado->utilizado) ? "Sim" : "Não"}}</td>
                                        <td>{{($preAprovado->origem) ? 'Import.' : 'Manual'}}</td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="6">Nenhum Pré-aprovado cadastrado!</td>
                                    </tr>
                                    @endforelse
                                    
                                </tbody>
                            </table>
                        </form>
                    </div>
                    {{ $preAprovados->onEachSide(0)->appends([Request::except('page')])->links() }}

                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts-footer')

@component('components.table-click')  
@endcomponent
<script type="text/javascript">
    $(document).ready(function($){
        $('#selectAll').click(function(e){    
            var table= $(e.target).closest('table');
            $('td input:checkbox',table).prop('checked',this.checked);
        });

        $('select[name="empresa_id"]').change(function(){
            //console.log($(this).children('option:selected').data('url'));
            var url = "{{ route('admin.pre-aprovados.index') }}";        
            
            if ($(this).children('option:selected').val())
                url+='?empresa='+encodeURIComponent($(this).children('option:selected').val());
            
            url = url.replace(/\&$/,'');
            
            window.location.href=url;
        });
    });
</script>

@endpush

@component('components.modal')
    
@endcomponent

@component('components.preloader')
            
@endcomponent